//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_PRODUCT_CreateID", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HiGirl360.Models.Member), "TAOKEPRODUCT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HiGirl360.Models.TAOKEPRODUCT), true)]
[assembly: EdmRelationshipAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HiGirl360.Models.TAOKECHANNEL), "TAOKECATEGORY", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HiGirl360.Models.TAOKECATEGORY), true)]
[assembly: EdmRelationshipAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HiGirl360.Models.TAOKECATEGORY), "TAOKECHANNEL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HiGirl360.Models.TAOKECHANNEL), true)]

#endregion

namespace HiGirl360.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class TaoKeEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“TaoKeEntities”部分中的连接字符串初始化新 TaoKeEntities 对象。
        /// </summary>
        public TaoKeEntities() : base("name=TaoKeEntities", "TaoKeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TaoKeEntities 对象。
        /// </summary>
        public TaoKeEntities(string connectionString) : base(connectionString, "TaoKeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TaoKeEntities 对象。
        /// </summary>
        public TaoKeEntities(EntityConnection connection) : base(connection, "TaoKeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Member> Member
        {
            get
            {
                if ((_Member == null))
                {
                    _Member = base.CreateObjectSet<Member>("Member");
                }
                return _Member;
            }
        }
        private ObjectSet<Member> _Member;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TAOKECATEGORY> TAOKECATEGORY
        {
            get
            {
                if ((_TAOKECATEGORY == null))
                {
                    _TAOKECATEGORY = base.CreateObjectSet<TAOKECATEGORY>("TAOKECATEGORY");
                }
                return _TAOKECATEGORY;
            }
        }
        private ObjectSet<TAOKECATEGORY> _TAOKECATEGORY;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TAOKECHANNEL> TAOKECHANNEL
        {
            get
            {
                if ((_TAOKECHANNEL == null))
                {
                    _TAOKECHANNEL = base.CreateObjectSet<TAOKECHANNEL>("TAOKECHANNEL");
                }
                return _TAOKECHANNEL;
            }
        }
        private ObjectSet<TAOKECHANNEL> _TAOKECHANNEL;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TAOKEPRODUCT> TAOKEPRODUCT
        {
            get
            {
                if ((_TAOKEPRODUCT == null))
                {
                    _TAOKEPRODUCT = base.CreateObjectSet<TAOKEPRODUCT>("TAOKEPRODUCT");
                }
                return _TAOKEPRODUCT;
            }
        }
        private ObjectSet<TAOKEPRODUCT> _TAOKEPRODUCT;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserFavorites> UserFavorites
        {
            get
            {
                if ((_UserFavorites == null))
                {
                    _UserFavorites = base.CreateObjectSet<UserFavorites>("UserFavorites");
                }
                return _UserFavorites;
            }
        }
        private ObjectSet<UserFavorites> _UserFavorites;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserProductComment> UserProductComment
        {
            get
            {
                if ((_UserProductComment == null))
                {
                    _UserProductComment = base.CreateObjectSet<UserProductComment>("UserProductComment");
                }
                return _UserProductComment;
            }
        }
        private ObjectSet<UserProductComment> _UserProductComment;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMember(Member member)
        {
            base.AddObject("Member", member);
        }
    
        /// <summary>
        /// 用于向 TAOKECATEGORY EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTAOKECATEGORY(TAOKECATEGORY tAOKECATEGORY)
        {
            base.AddObject("TAOKECATEGORY", tAOKECATEGORY);
        }
    
        /// <summary>
        /// 用于向 TAOKECHANNEL EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTAOKECHANNEL(TAOKECHANNEL tAOKECHANNEL)
        {
            base.AddObject("TAOKECHANNEL", tAOKECHANNEL);
        }
    
        /// <summary>
        /// 用于向 TAOKEPRODUCT EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTAOKEPRODUCT(TAOKEPRODUCT tAOKEPRODUCT)
        {
            base.AddObject("TAOKEPRODUCT", tAOKEPRODUCT);
        }
    
        /// <summary>
        /// 用于向 UserFavorites EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserFavorites(UserFavorites userFavorites)
        {
            base.AddObject("UserFavorites", userFavorites);
        }
    
        /// <summary>
        /// 用于向 UserProductComment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserProductComment(UserProductComment userProductComment)
        {
            base.AddObject("UserProductComment", userProductComment);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Member 对象。
        /// </summary>
        /// <param name="memberID">MemberID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="userPassword">UserPassword 属性的初始值。</param>
        /// <param name="user_Status">User_Status 属性的初始值。</param>
        public static Member CreateMember(global::System.Int32 memberID, global::System.String userName, global::System.String userPassword, global::System.String user_Status)
        {
            Member member = new Member();
            member.MemberID = memberID;
            member.UserName = userName;
            member.UserPassword = userPassword;
            member.User_Status = user_Status;
            return member;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserNickName
        {
            get
            {
                return _UserNickName;
            }
            set
            {
                OnUserNickNameChanging(value);
                ReportPropertyChanging("UserNickName");
                _UserNickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserNickName");
                OnUserNickNameChanged();
            }
        }
        private global::System.String _UserNickName;
        partial void OnUserNickNameChanging(global::System.String value);
        partial void OnUserNickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaoKeID
        {
            get
            {
                return _TaoKeID;
            }
            set
            {
                OnTaoKeIDChanging(value);
                ReportPropertyChanging("TaoKeID");
                _TaoKeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaoKeID");
                OnTaoKeIDChanged();
            }
        }
        private global::System.String _TaoKeID;
        partial void OnTaoKeIDChanging(global::System.String value);
        partial void OnTaoKeIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNo
        {
            get
            {
                return _PhoneNo;
            }
            set
            {
                OnPhoneNoChanging(value);
                ReportPropertyChanging("PhoneNo");
                _PhoneNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNo");
                OnPhoneNoChanged();
            }
        }
        private global::System.String _PhoneNo;
        partial void OnPhoneNoChanging(global::System.String value);
        partial void OnPhoneNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPic
        {
            get
            {
                return _UserPic;
            }
            set
            {
                OnUserPicChanging(value);
                ReportPropertyChanging("UserPic");
                _UserPic = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPic");
                OnUserPicChanged();
            }
        }
        private global::System.String _UserPic;
        partial void OnUserPicChanging(global::System.String value);
        partial void OnUserPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserDesc
        {
            get
            {
                return _UserDesc;
            }
            set
            {
                OnUserDescChanging(value);
                ReportPropertyChanging("UserDesc");
                _UserDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserDesc");
                OnUserDescChanged();
            }
        }
        private global::System.String _UserDesc;
        partial void OnUserDescChanging(global::System.String value);
        partial void OnUserDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LastMonthMoney
        {
            get
            {
                return _LastMonthMoney;
            }
            set
            {
                OnLastMonthMoneyChanging(value);
                ReportPropertyChanging("LastMonthMoney");
                _LastMonthMoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastMonthMoney");
                OnLastMonthMoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _LastMonthMoney;
        partial void OnLastMonthMoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnLastMonthMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RecommendUserID
        {
            get
            {
                return _RecommendUserID;
            }
            set
            {
                OnRecommendUserIDChanging(value);
                ReportPropertyChanging("RecommendUserID");
                _RecommendUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecommendUserID");
                OnRecommendUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RecommendUserID;
        partial void OnRecommendUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnRecommendUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_Status
        {
            get
            {
                return _User_Status;
            }
            set
            {
                OnUser_StatusChanging(value);
                ReportPropertyChanging("User_Status");
                _User_Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_Status");
                OnUser_StatusChanged();
            }
        }
        private global::System.String _User_Status;
        partial void OnUser_StatusChanging(global::System.String value);
        partial void OnUser_StatusChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_PRODUCT_CreateID", "TAOKEPRODUCT")]
        public EntityCollection<TAOKEPRODUCT> TAOKEPRODUCT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAOKEPRODUCT>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "TAOKEPRODUCT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAOKEPRODUCT>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "TAOKEPRODUCT", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="TAOKECATEGORY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAOKECATEGORY : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TAOKECATEGORY 对象。
        /// </summary>
        /// <param name="cateID">CateID 属性的初始值。</param>
        /// <param name="cateName">CateName 属性的初始值。</param>
        /// <param name="parentCateID">ParentCateID 属性的初始值。</param>
        /// <param name="cateClickCount">CateClickCount 属性的初始值。</param>
        /// <param name="cateSort">CateSort 属性的初始值。</param>
        /// <param name="cateStatus">CateStatus 属性的初始值。</param>
        public static TAOKECATEGORY CreateTAOKECATEGORY(global::System.Int32 cateID, global::System.String cateName, global::System.Int32 parentCateID, global::System.Int32 cateClickCount, global::System.Int32 cateSort, global::System.String cateStatus)
        {
            TAOKECATEGORY tAOKECATEGORY = new TAOKECATEGORY();
            tAOKECATEGORY.CateID = cateID;
            tAOKECATEGORY.CateName = cateName;
            tAOKECATEGORY.ParentCateID = parentCateID;
            tAOKECATEGORY.CateClickCount = cateClickCount;
            tAOKECATEGORY.CateSort = cateSort;
            tAOKECATEGORY.CateStatus = cateStatus;
            return tAOKECATEGORY;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CateID
        {
            get
            {
                return _CateID;
            }
            set
            {
                if (_CateID != value)
                {
                    OnCateIDChanging(value);
                    ReportPropertyChanging("CateID");
                    _CateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CateID");
                    OnCateIDChanged();
                }
            }
        }
        private global::System.Int32 _CateID;
        partial void OnCateIDChanging(global::System.Int32 value);
        partial void OnCateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CateName
        {
            get
            {
                return _CateName;
            }
            set
            {
                OnCateNameChanging(value);
                ReportPropertyChanging("CateName");
                _CateName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CateName");
                OnCateNameChanged();
            }
        }
        private global::System.String _CateName;
        partial void OnCateNameChanging(global::System.String value);
        partial void OnCateNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CateDesc
        {
            get
            {
                return _CateDesc;
            }
            set
            {
                OnCateDescChanging(value);
                ReportPropertyChanging("CateDesc");
                _CateDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CateDesc");
                OnCateDescChanged();
            }
        }
        private global::System.String _CateDesc;
        partial void OnCateDescChanging(global::System.String value);
        partial void OnCateDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentCateID
        {
            get
            {
                return _ParentCateID;
            }
            set
            {
                OnParentCateIDChanging(value);
                ReportPropertyChanging("ParentCateID");
                _ParentCateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentCateID");
                OnParentCateIDChanged();
            }
        }
        private global::System.Int32 _ParentCateID;
        partial void OnParentCateIDChanging(global::System.Int32 value);
        partial void OnParentCateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CateChannelID
        {
            get
            {
                return _CateChannelID;
            }
            set
            {
                OnCateChannelIDChanging(value);
                ReportPropertyChanging("CateChannelID");
                _CateChannelID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CateChannelID");
                OnCateChannelIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CateChannelID;
        partial void OnCateChannelIDChanging(Nullable<global::System.Int32> value);
        partial void OnCateChannelIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CateClickCount
        {
            get
            {
                return _CateClickCount;
            }
            set
            {
                OnCateClickCountChanging(value);
                ReportPropertyChanging("CateClickCount");
                _CateClickCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CateClickCount");
                OnCateClickCountChanged();
            }
        }
        private global::System.Int32 _CateClickCount;
        partial void OnCateClickCountChanging(global::System.Int32 value);
        partial void OnCateClickCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CateSort
        {
            get
            {
                return _CateSort;
            }
            set
            {
                OnCateSortChanging(value);
                ReportPropertyChanging("CateSort");
                _CateSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CateSort");
                OnCateSortChanged();
            }
        }
        private global::System.Int32 _CateSort;
        partial void OnCateSortChanging(global::System.Int32 value);
        partial void OnCateSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CateStatus
        {
            get
            {
                return _CateStatus;
            }
            set
            {
                OnCateStatusChanging(value);
                ReportPropertyChanging("CateStatus");
                _CateStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CateStatus");
                OnCateStatusChanged();
            }
        }
        private global::System.String _CateStatus;
        partial void OnCateStatusChanging(global::System.String value);
        partial void OnCateStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL")]
        public TAOKECHANNEL TAOKECHANNEL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TAOKECHANNEL> TAOKECHANNELReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECHANNEL", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CHANNEL_CateID", "TAOKECHANNEL")]
        public EntityCollection<TAOKECHANNEL> TAOKECHANNEL1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECHANNEL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAOKECHANNEL>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECHANNEL", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="TAOKECHANNEL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAOKECHANNEL : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TAOKECHANNEL 对象。
        /// </summary>
        /// <param name="channelID">ChannelID 属性的初始值。</param>
        /// <param name="channelName">ChannelName 属性的初始值。</param>
        /// <param name="channelSort">ChannelSort 属性的初始值。</param>
        /// <param name="channelStatus">ChannelStatus 属性的初始值。</param>
        public static TAOKECHANNEL CreateTAOKECHANNEL(global::System.Int32 channelID, global::System.String channelName, global::System.Int32 channelSort, global::System.String channelStatus)
        {
            TAOKECHANNEL tAOKECHANNEL = new TAOKECHANNEL();
            tAOKECHANNEL.ChannelID = channelID;
            tAOKECHANNEL.ChannelName = channelName;
            tAOKECHANNEL.ChannelSort = channelSort;
            tAOKECHANNEL.ChannelStatus = channelStatus;
            return tAOKECHANNEL;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChannelID
        {
            get
            {
                return _ChannelID;
            }
            set
            {
                if (_ChannelID != value)
                {
                    OnChannelIDChanging(value);
                    ReportPropertyChanging("ChannelID");
                    _ChannelID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ChannelID");
                    OnChannelIDChanged();
                }
            }
        }
        private global::System.Int32 _ChannelID;
        partial void OnChannelIDChanging(global::System.Int32 value);
        partial void OnChannelIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChannelName
        {
            get
            {
                return _ChannelName;
            }
            set
            {
                OnChannelNameChanging(value);
                ReportPropertyChanging("ChannelName");
                _ChannelName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChannelName");
                OnChannelNameChanged();
            }
        }
        private global::System.String _ChannelName;
        partial void OnChannelNameChanging(global::System.String value);
        partial void OnChannelNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChannelDesc
        {
            get
            {
                return _ChannelDesc;
            }
            set
            {
                OnChannelDescChanging(value);
                ReportPropertyChanging("ChannelDesc");
                _ChannelDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChannelDesc");
                OnChannelDescChanged();
            }
        }
        private global::System.String _ChannelDesc;
        partial void OnChannelDescChanging(global::System.String value);
        partial void OnChannelDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentCateID
        {
            get
            {
                return _ParentCateID;
            }
            set
            {
                OnParentCateIDChanging(value);
                ReportPropertyChanging("ParentCateID");
                _ParentCateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentCateID");
                OnParentCateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentCateID;
        partial void OnParentCateIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentCateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ChannelSort
        {
            get
            {
                return _ChannelSort;
            }
            set
            {
                OnChannelSortChanging(value);
                ReportPropertyChanging("ChannelSort");
                _ChannelSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChannelSort");
                OnChannelSortChanged();
            }
        }
        private global::System.Int32 _ChannelSort;
        partial void OnChannelSortChanging(global::System.Int32 value);
        partial void OnChannelSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChannelStatus
        {
            get
            {
                return _ChannelStatus;
            }
            set
            {
                OnChannelStatusChanging(value);
                ReportPropertyChanging("ChannelStatus");
                _ChannelStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChannelStatus");
                OnChannelStatusChanged();
            }
        }
        private global::System.String _ChannelStatus;
        partial void OnChannelStatusChanging(global::System.String value);
        partial void OnChannelStatusChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CATEGORY_ChannelID", "TAOKECATEGORY")]
        public EntityCollection<TAOKECATEGORY> TAOKECATEGORY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECATEGORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CATEGORY_ChannelID", "TAOKECATEGORY", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY")]
        public TAOKECATEGORY TAOKECATEGORY1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TAOKECATEGORY> TAOKECATEGORY1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TAOKECATEGORY>("HiGirl360_TaoKeModel.FK_TAOKE_CHANNEL_CateID", "TAOKECATEGORY", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="TAOKEPRODUCT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TAOKEPRODUCT : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TAOKEPRODUCT 对象。
        /// </summary>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="productTitle">ProductTitle 属性的初始值。</param>
        /// <param name="productPic">ProductPic 属性的初始值。</param>
        /// <param name="productPrice">ProductPrice 属性的初始值。</param>
        /// <param name="productUrl">ProductUrl 属性的初始值。</param>
        /// <param name="shopName">ShopName 属性的初始值。</param>
        /// <param name="shopLevel">ShopLevel 属性的初始值。</param>
        /// <param name="shopUrl">ShopUrl 属性的初始值。</param>
        /// <param name="productStatus">ProductStatus 属性的初始值。</param>
        /// <param name="cateCode">CateCode 属性的初始值。</param>
        /// <param name="createUserID">CreateUserID 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static TAOKEPRODUCT CreateTAOKEPRODUCT(global::System.String productID, global::System.String productTitle, global::System.String productPic, global::System.Decimal productPrice, global::System.String productUrl, global::System.String shopName, global::System.Int16 shopLevel, global::System.String shopUrl, global::System.String productStatus, global::System.Int32 cateCode, global::System.Int32 createUserID, global::System.DateTime createTime)
        {
            TAOKEPRODUCT tAOKEPRODUCT = new TAOKEPRODUCT();
            tAOKEPRODUCT.ProductID = productID;
            tAOKEPRODUCT.ProductTitle = productTitle;
            tAOKEPRODUCT.ProductPic = productPic;
            tAOKEPRODUCT.ProductPrice = productPrice;
            tAOKEPRODUCT.ProductUrl = productUrl;
            tAOKEPRODUCT.ShopName = shopName;
            tAOKEPRODUCT.ShopLevel = shopLevel;
            tAOKEPRODUCT.ShopUrl = shopUrl;
            tAOKEPRODUCT.ProductStatus = productStatus;
            tAOKEPRODUCT.CateCode = cateCode;
            tAOKEPRODUCT.CreateUserID = createUserID;
            tAOKEPRODUCT.CreateTime = createTime;
            return tAOKEPRODUCT;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.String _ProductID;
        partial void OnProductIDChanging(global::System.String value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductTitle
        {
            get
            {
                return _ProductTitle;
            }
            set
            {
                OnProductTitleChanging(value);
                ReportPropertyChanging("ProductTitle");
                _ProductTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductTitle");
                OnProductTitleChanged();
            }
        }
        private global::System.String _ProductTitle;
        partial void OnProductTitleChanging(global::System.String value);
        partial void OnProductTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductPic
        {
            get
            {
                return _ProductPic;
            }
            set
            {
                OnProductPicChanging(value);
                ReportPropertyChanging("ProductPic");
                _ProductPic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductPic");
                OnProductPicChanged();
            }
        }
        private global::System.String _ProductPic;
        partial void OnProductPicChanging(global::System.String value);
        partial void OnProductPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private global::System.Decimal _ProductPrice;
        partial void OnProductPriceChanging(global::System.Decimal value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ProductCouponPrice
        {
            get
            {
                return _ProductCouponPrice;
            }
            set
            {
                OnProductCouponPriceChanging(value);
                ReportPropertyChanging("ProductCouponPrice");
                _ProductCouponPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductCouponPrice");
                OnProductCouponPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _ProductCouponPrice;
        partial void OnProductCouponPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnProductCouponPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CommissionRate
        {
            get
            {
                return _CommissionRate;
            }
            set
            {
                OnCommissionRateChanging(value);
                ReportPropertyChanging("CommissionRate");
                _CommissionRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommissionRate");
                OnCommissionRateChanged();
            }
        }
        private Nullable<global::System.Int16> _CommissionRate;
        partial void OnCommissionRateChanging(Nullable<global::System.Int16> value);
        partial void OnCommissionRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductUrl
        {
            get
            {
                return _ProductUrl;
            }
            set
            {
                OnProductUrlChanging(value);
                ReportPropertyChanging("ProductUrl");
                _ProductUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductUrl");
                OnProductUrlChanged();
            }
        }
        private global::System.String _ProductUrl;
        partial void OnProductUrlChanging(global::System.String value);
        partial void OnProductUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShopName
        {
            get
            {
                return _ShopName;
            }
            set
            {
                OnShopNameChanging(value);
                ReportPropertyChanging("ShopName");
                _ShopName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShopName");
                OnShopNameChanged();
            }
        }
        private global::System.String _ShopName;
        partial void OnShopNameChanging(global::System.String value);
        partial void OnShopNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ShopLevel
        {
            get
            {
                return _ShopLevel;
            }
            set
            {
                OnShopLevelChanging(value);
                ReportPropertyChanging("ShopLevel");
                _ShopLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShopLevel");
                OnShopLevelChanged();
            }
        }
        private global::System.Int16 _ShopLevel;
        partial void OnShopLevelChanging(global::System.Int16 value);
        partial void OnShopLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShopUrl
        {
            get
            {
                return _ShopUrl;
            }
            set
            {
                OnShopUrlChanging(value);
                ReportPropertyChanging("ShopUrl");
                _ShopUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShopUrl");
                OnShopUrlChanged();
            }
        }
        private global::System.String _ShopUrl;
        partial void OnShopUrlChanging(global::System.String value);
        partial void OnShopUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductStatus
        {
            get
            {
                return _ProductStatus;
            }
            set
            {
                OnProductStatusChanging(value);
                ReportPropertyChanging("ProductStatus");
                _ProductStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductStatus");
                OnProductStatusChanged();
            }
        }
        private global::System.String _ProductStatus;
        partial void OnProductStatusChanging(global::System.String value);
        partial void OnProductStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CateCode
        {
            get
            {
                return _CateCode;
            }
            set
            {
                OnCateCodeChanging(value);
                ReportPropertyChanging("CateCode");
                _CateCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CateCode");
                OnCateCodeChanged();
            }
        }
        private global::System.Int32 _CateCode;
        partial void OnCateCodeChanging(global::System.Int32 value);
        partial void OnCateCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreateUserID
        {
            get
            {
                return _CreateUserID;
            }
            set
            {
                OnCreateUserIDChanging(value);
                ReportPropertyChanging("CreateUserID");
                _CreateUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateUserID");
                OnCreateUserIDChanged();
            }
        }
        private global::System.Int32 _CreateUserID;
        partial void OnCreateUserIDChanging(global::System.Int32 value);
        partial void OnCreateUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserReCommendDesc
        {
            get
            {
                return _UserReCommendDesc;
            }
            set
            {
                OnUserReCommendDescChanging(value);
                ReportPropertyChanging("UserReCommendDesc");
                _UserReCommendDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserReCommendDesc");
                OnUserReCommendDescChanged();
            }
        }
        private global::System.String _UserReCommendDesc;
        partial void OnUserReCommendDescChanging(global::System.String value);
        partial void OnUserReCommendDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastUpdateUser
        {
            get
            {
                return _LastUpdateUser;
            }
            set
            {
                OnLastUpdateUserChanging(value);
                ReportPropertyChanging("LastUpdateUser");
                _LastUpdateUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastUpdateUser");
                OnLastUpdateUserChanged();
            }
        }
        private global::System.String _LastUpdateUser;
        partial void OnLastUpdateUserChanging(global::System.String value);
        partial void OnLastUpdateUserChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateTime
        {
            get
            {
                return _LastUpdateTime;
            }
            set
            {
                OnLastUpdateTimeChanging(value);
                ReportPropertyChanging("LastUpdateTime");
                _LastUpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateTime");
                OnLastUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateTimeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HiGirl360_TaoKeModel", "FK_TAOKE_PRODUCT_CreateID", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "Member").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("HiGirl360_TaoKeModel.FK_TAOKE_PRODUCT_CreateID", "Member", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="UserFavorites")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserFavorites : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserFavorites 对象。
        /// </summary>
        /// <param name="memberID">MemberID 属性的初始值。</param>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="productTitle">ProductTitle 属性的初始值。</param>
        /// <param name="productDesc">ProductDesc 属性的初始值。</param>
        /// <param name="productShop">ProductShop 属性的初始值。</param>
        /// <param name="productCateID">ProductCateID 属性的初始值。</param>
        /// <param name="prodcutPrice">ProdcutPrice 属性的初始值。</param>
        /// <param name="productNowPrice">ProductNowPrice 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static UserFavorites CreateUserFavorites(global::System.Int32 memberID, global::System.String productID, global::System.String productTitle, global::System.String productDesc, global::System.String productShop, global::System.String productCateID, global::System.Decimal prodcutPrice, global::System.Decimal productNowPrice, global::System.DateTime createTime)
        {
            UserFavorites userFavorites = new UserFavorites();
            userFavorites.MemberID = memberID;
            userFavorites.ProductID = productID;
            userFavorites.ProductTitle = productTitle;
            userFavorites.ProductDesc = productDesc;
            userFavorites.ProductShop = productShop;
            userFavorites.ProductCateID = productCateID;
            userFavorites.ProdcutPrice = prodcutPrice;
            userFavorites.ProductNowPrice = productNowPrice;
            userFavorites.CreateTime = createTime;
            return userFavorites;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.String _ProductID;
        partial void OnProductIDChanging(global::System.String value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductTitle
        {
            get
            {
                return _ProductTitle;
            }
            set
            {
                OnProductTitleChanging(value);
                ReportPropertyChanging("ProductTitle");
                _ProductTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductTitle");
                OnProductTitleChanged();
            }
        }
        private global::System.String _ProductTitle;
        partial void OnProductTitleChanging(global::System.String value);
        partial void OnProductTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductDesc
        {
            get
            {
                return _ProductDesc;
            }
            set
            {
                OnProductDescChanging(value);
                ReportPropertyChanging("ProductDesc");
                _ProductDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductDesc");
                OnProductDescChanged();
            }
        }
        private global::System.String _ProductDesc;
        partial void OnProductDescChanging(global::System.String value);
        partial void OnProductDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductShop
        {
            get
            {
                return _ProductShop;
            }
            set
            {
                OnProductShopChanging(value);
                ReportPropertyChanging("ProductShop");
                _ProductShop = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductShop");
                OnProductShopChanged();
            }
        }
        private global::System.String _ProductShop;
        partial void OnProductShopChanging(global::System.String value);
        partial void OnProductShopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCateID
        {
            get
            {
                return _ProductCateID;
            }
            set
            {
                OnProductCateIDChanging(value);
                ReportPropertyChanging("ProductCateID");
                _ProductCateID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductCateID");
                OnProductCateIDChanged();
            }
        }
        private global::System.String _ProductCateID;
        partial void OnProductCateIDChanging(global::System.String value);
        partial void OnProductCateIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ProdcutPrice
        {
            get
            {
                return _ProdcutPrice;
            }
            set
            {
                OnProdcutPriceChanging(value);
                ReportPropertyChanging("ProdcutPrice");
                _ProdcutPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProdcutPrice");
                OnProdcutPriceChanged();
            }
        }
        private global::System.Decimal _ProdcutPrice;
        partial void OnProdcutPriceChanging(global::System.Decimal value);
        partial void OnProdcutPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ProductNowPrice
        {
            get
            {
                return _ProductNowPrice;
            }
            set
            {
                OnProductNowPriceChanging(value);
                ReportPropertyChanging("ProductNowPrice");
                _ProductNowPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductNowPrice");
                OnProductNowPriceChanged();
            }
        }
        private global::System.Decimal _ProductNowPrice;
        partial void OnProductNowPriceChanging(global::System.Decimal value);
        partial void OnProductNowPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdateTime
        {
            get
            {
                return _LastUpdateTime;
            }
            set
            {
                OnLastUpdateTimeChanging(value);
                ReportPropertyChanging("LastUpdateTime");
                _LastUpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdateTime");
                OnLastUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdateTime;
        partial void OnLastUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HiGirl360_TaoKeModel", Name="UserProductComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProductComment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserProductComment 对象。
        /// </summary>
        /// <param name="memberID">MemberID 属性的初始值。</param>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="commentTitle">CommentTitle 属性的初始值。</param>
        /// <param name="commentBody">CommentBody 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static UserProductComment CreateUserProductComment(global::System.Int32 memberID, global::System.String productID, global::System.String commentTitle, global::System.String commentBody, global::System.DateTime createTime, global::System.String status)
        {
            UserProductComment userProductComment = new UserProductComment();
            userProductComment.MemberID = memberID;
            userProductComment.ProductID = productID;
            userProductComment.CommentTitle = commentTitle;
            userProductComment.CommentBody = commentBody;
            userProductComment.CreateTime = createTime;
            userProductComment.Status = status;
            return userProductComment;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.String _ProductID;
        partial void OnProductIDChanging(global::System.String value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentTitle
        {
            get
            {
                return _CommentTitle;
            }
            set
            {
                OnCommentTitleChanging(value);
                ReportPropertyChanging("CommentTitle");
                _CommentTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentTitle");
                OnCommentTitleChanged();
            }
        }
        private global::System.String _CommentTitle;
        partial void OnCommentTitleChanging(global::System.String value);
        partial void OnCommentTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentBody
        {
            get
            {
                return _CommentBody;
            }
            set
            {
                OnCommentBodyChanging(value);
                ReportPropertyChanging("CommentBody");
                _CommentBody = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CommentBody");
                OnCommentBodyChanged();
            }
        }
        private global::System.String _CommentBody;
        partial void OnCommentBodyChanging(global::System.String value);
        partial void OnCommentBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
    }

    #endregion
    
}
